### ISSUE TITLE
PIL vs OpenCV

### ISSUE THREAD

**Issue by davidc9320sg** [human-centered-ai-lab/app-kandinsky-pattern-generator#4]
_Question_

Hi! I just started exploring and playing around with the generator code.
If I am reading the code correctly, I found that there are two approaches to drawing the figures.

- the demo in the `.ipynb` notebook defines functions for the shapes and draws them on the figure using PIL
  - OpenCV is instead used only in the last block as a test
- the `kpgen.py` script relies on the functions in OpenCV to draw the shapes (through `generateClasses` -> `KandinskyUniverse.kandinskyFigureAsImage`)
  - the figures are then converted to PIL Images before saving
- in both, the `overlap` function appears to rely on PIL

Are there any major differences between the approaches? Which one is advised when creating a new set of figures? It would appear that PIL is sufficient for task.

Thank you in advance for the support!

**Comment by lomadi** [comment]
both should just illustrate the approach, wie used initially PIL and is sufficient, OpenCV had a better antialiasing function, which was necessary in some validator, therefore it was used. 

For a real "production" version we plan to include a flexible output pipeline including vector formats , e.g. SVG

**Comment by davidc9320sg** [comment]
I see, thank you for the reply!
